spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - name: JwtAuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: JwtAuthenticationFilter

        - id: startup-service
          uri: lb://STARTUP-SERVICE
          predicates:
            - Path=/startups/**
          filters:
            - name: JwtAuthenticationFilter

        - id: investment-service
          uri: lb://INVESTMENT-SERVICE
          predicates:
            - Path=/investments/**
          filters:
            - name: JwtAuthenticationFilter

        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/teams/**
          filters:
            - name: JwtAuthenticationFilter

        - id: messaging-service
          uri: lb://MESSAGING-SERVICE
          predicates:
            - Path=/messages/**
          filters:
            - name: JwtAuthenticationFilter

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - name: JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
logging:
  level:
    com.capgemini.apigateway: INFO
