spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/founderlink_investments
    username: snehalsuman
    password: Snehal@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      startup-service:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 10s
        failureRateThreshold: 50

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

rabbitmq:
  exchange: founderlink.exchange
  queue:
    investment-created: investment.created.queue
    investment-approved: investment.approved.queue
  routing-key:
    investment-created: investment.created
    investment-approved: investment.approved

logging:
  level:
    com.capgemini.investment: INFO
    io.github.resilience4j: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
